version: '3.4'

services:
  traefik:
    image: 'traefik:montdor-alpine'
    restart: 'always'
    networks:
      - proxy
    ports:
      - '80:80'
      - '8888:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.yaml:/etc/traefik/traefik.yaml:ro'

networks:
  proxy:
    external: true
